apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../../base/memo
  - ingress.yaml

patchesStrategicMerge:
  - patch.yaml

namePrefix: prod-

commonLabels:
  environment: production
  managed-by: argocd

images:
  - name: ghcr.io/nicolashuberty/full-stack-k3s/memo-app
    newTag: production
  - name: ghcr.io/nicolashuberty/full-stack-k3s/memo-worker
    newTag: production

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
