apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memo-app-dev

namePrefix: dev-
nameSuffix: ""

bases:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yaml
  - replica-patch.yaml

images:
  - name: ghcr.io/nicolashuberty/memo-app
    newTag: dev
  - name: ghcr.io/nicolashuberty/memo-worker
    newTag: dev

commonLabels:
  environment: dev

patches:
  - target:
      kind: Namespace
      name: memo-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: memo-app-dev
  - target:
      kind: ExternalSecret
      name: memo-secrets
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: memo-app/dev
      - op: replace
        path: /spec/data/1/remoteRef/key
        value: memo-app/dev
      - op: replace
        path: /spec/data/2/remoteRef/key
        value: memo-app/dev
      - op: replace
        path: /spec/data/3/remoteRef/key
        value: memo-app/dev
      - op: replace
        path: /spec/data/4/remoteRef/key
        value: memo-app/dev
      - op: replace
        path: /spec/data/5/remoteRef/key
        value: memo-app/dev
