apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-frontend
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-06T16:35:00Z"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-worker
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-06T16:35:00Z"
