apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memo-secrets
  namespace: memo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: memo-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-user
      remoteRef:
        key: memo-app
        property: postgres-user
    - secretKey: postgres-password
      remoteRef:
        key: memo-app
        property: postgres-password
    - secretKey: database-url
      remoteRef:
        key: memo-app
        property: database-url
    - secretKey: minio-root-user
      remoteRef:
        key: memo-app
        property: minio-root-user
    - secretKey: minio-root-password
      remoteRef:
        key: memo-app
        property: minio-root-password
    - secretKey: mistral-api-key
      remoteRef:
        key: memo-app
        property: mistral-api-key
