apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memo-app

resources:
  - namespace.yaml
  - externalsecret.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - frontend.yaml
  - worker.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: memo-app
  app.kubernetes.io/part-of: memo-app
