apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-frontend
  namespace: memo-app-staging
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-worker
  namespace: memo-app-staging
spec:
  replicas: 2
