apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memo-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "memo.docuralis.com"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - memo.docuralis.com
      secretName: memo-prod-tls
  rules:
    - host: memo.docuralis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memo
                port:
                  number: 3000
